version: '3.7'

services:

  backend:
    build: ./
    ports:
      - 8001:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./:/usr/src/app
    depends_on:
      - 'mysqldb'
    environment:
      DB_HOST: mysqldb
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
      DB_DATABASE: $DB_DATABASE
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'guanedog'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    